### ISSUE TITLE
slight change to UI every region change

### ISSUE THREAD

**Issue by ajlb** [n-lambert/Inn-At-The-Edge-of-Copyright#113]
Each time a player enters a different location/region the fexbox around the player text box displays a different pattern indicative of the region.

- [x] The Inn
- [x] Pumpkin Patch
- [x] Forest
- [x] Caverns
- [x] Cavern Lake
- [x] Cavern Elevator
- [x] Town/Cross Roads
- [x] Meadow
- [x] Clouds
- [x] Mountains
- [x] Space Ship

**Comment by talianajera** [comment]
this task has been completed as of today November 27th.
