### ISSUE TITLE
Http vs Https

### ISSUE THREAD

**Issue by NTKonzen** [n-lambert/Inn-At-The-Edge-of-Copyright#170]
When players attempt to access the site on http:// they get errors and are not rerouted to https:// by default

**Comment by rebgrasshopper** [comment]
We have so far tried two tactics - 
1. using a redirect: 
`app.get('*', function(req, res) {  
  res.redirect('https://' + req.headers.host + req.url).sendFile(path.join(__dirname, "./client/build/index.html"));
})`

2. using an npm package - express-sslify.

So far, neither seems to forcibly redirect you. We are going to deploy with sslify and see what happens
