### ISSUE TITLE
Roomba running through room when nothing has been dropped or picked up

### ISSUE THREAD

**Issue by NTKonzen** [n-lambert/Inn-At-The-Edge-of-Copyright#239]
No items were dropped or picked up but this message displayed twice about 5 minutes apart

<img width="743" alt="Screen Shot 2020-12-18 at 12 47 19 AM" src="https://user-images.githubusercontent.com/66763982/102594129-a45c0e80-40ca-11eb-874e-12f69b22677e.png">

**Comment by rebgrasshopper** [comment]
I believe the roomba is now working correctly, and that this issue was caused by roomba only editing items one at a time.
