### ISSUE TITLE
That's a lotta monsters!

### ISSUE THREAD

**Issue by NTKonzen** [n-lambert/Inn-At-The-Edge-of-Copyright#249]
After defeating a single monster at the Murky Pond, everything seemed fine until the monster sweeper ran and [figure 1](#figure1) was displayed

### Figure 1
<img width="246" alt="Screen Shot 2021-01-18 at 4 27 15 PM" src="https://user-images.githubusercontent.com/66763982/104973670-4319aa80-59aa-11eb-821c-6787c55d2633.png">

**Comment by rebgrasshopper** [comment]
Issue was caused by duplicate monster IDs in seed
