### ISSUE TITLE
NPC full interaction

### ISSUE THREAD

**Issue by rebgrasshopper** [n-lambert/Inn-At-The-Edge-of-Copyright#98]

**Comment by jen6one9** [comment]
a. NPC move about the world
	b. Speech interaction can still be local
	c. Multiple people in a location - 
		Figure out the release and reset the pin after the user has scrolled from the bottom (updating the description)

**Comment by NTKonzen** [comment]
I'm currently experimenting with Socket.io as a possible form of NPC interaction.

**Comment by NTKonzen** [comment]
So in an attempt to learn how socket.io works, I've sort of rebuilt my own socket.io based chat application. After talking with Nancy and Plover it seems that it would be a good idea to port the full application to socket.io in place of PubNub. I'm currently working on porting my text chat app to React to see how the two libraries interact
